trigger:
  - main

parameters:
  - name: NodeVersion
    displayName: Node.js Version
    type: string
    default: '16.x'
    values:
      - 16.x
      - 18.x

variables:
  azureSubscription: '009e80bd-57d1-4575-85c2-b3db5596b394'
  imageRepository: 'fancyapp'
  containerRegistry: 'fancyapp.azurecr.io'

stages:
  - stage: ValidatePR
    condition: and(ne(variables['Build.SourceBranch'], 'refs/heads/main'), eq(variables['Build.Reason'], 'PullRequest'))
    displayName: Validate PR
    jobs:
      - job: BuildApplication
        displayName: Build Application
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: ${{ parameters.NodeVersion }}
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            displayName: 'Lint application'
            inputs:
              command: custom
              customCommand: 'run lint-all'
          - task: Npm@1
            displayName: 'Build NX application'
            inputs:
              command: custom
              customCommand: 'run build'
          - task: Npm@1
            displayName: 'Run tests with code coverage'
            inputs:
              command: custom
              customCommand: 'run test-coverage'
          - task: PublishTestResults@2
            inputs:
              searchFolder: $(System.DefaultWorkingDirectory)/coverage
              testResultsFiles: '**/junit.xml'
              mergeTestResults: true
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/combined-coverage.xml

  - stage: BuildTest
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    dependsOn: [ ]
    displayName: 'Build application for Test Environment'
    jobs:
      - job: BuildTestApp
        displayName: Build App
        steps:
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: ${{ parameters.NodeVersion }}
          - task: Npm@1
            inputs:
              command: 'install'
          - task: Npm@1
            displayName: 'Lint application'
            inputs:
              command: custom
              customCommand: 'run lint-all'
          - task: Npm@1
            displayName: 'Build NX application'
            inputs:
              command: custom
              customCommand: 'run build'
          - task: Npm@1
            displayName: 'Run tests with code coverage'
            inputs:
              command: custom
              customCommand: 'run test-coverage'
          - task: PublishTestResults@2
            inputs:
              searchFolder: $(System.DefaultWorkingDirectory)/coverage
              testResultsFiles: '**/junit.xml'
              mergeTestResults: true
          - task: PublishCodeCoverageResults@1
            inputs:
              codeCoverageTool: Cobertura
              summaryFileLocation: $(System.DefaultWorkingDirectory)/coverage/combined-coverage.xml
          - task: ArchiveFiles@2
            inputs:
              rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/fancy-app/'
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
              replaceExistingArchive: true
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              ArtifactName: 'drop'

  - stage: DeploymentTest
    dependsOn: [ BuildTest ]
    displayName: Deploy Application to Test
    jobs:
      - deployment: TestRelease
        displayName: 'Deployment Process'
        environment: 'FancyApp-Test'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: 'Deploy App Service'
                  inputs:
                    azureSubscription: 'FancyAppTestServiceConnection'
                    resourceGroupName: 'fancy-app-test'
                    appName: 'fancy-app-test'
                    appType: webAppLinux
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

# if running app service in docker mode, after pushing docker image the app service must be restarted using hooks or following task
#                - task: AzureAppServiceManage@0
#                  inputs:
#                    azureSubscription: ${{ variables['azureSubscription'] }}
#                    action: 'Restart Azure App Service'
#                    webAppName: 'fancy-app-test'
